CREATE USER 'ggpserver'@'localhost' IDENTIFIED BY 'UnvdhZcyGPYFKUJZ';

GRANT USAGE ON * . * TO 'ggpserver'@'localhost' IDENTIFIED BY 'UnvdhZcyGPYFKUJZ' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `ggpserver` . * TO 'ggpserver'@'localhost';
