
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Jan 08 02:59:26 CET 2007
//----------------------------------------------------

package de.tu_dresden.inf.ggp06_2.parser;

/** CUP generated class containing symbol constants. */
public class preKIFSymbols {
  /* terminals */
  public static final int CONSTANT = 5;
  public static final int error = 1;
  public static final int PREDICATE = 6;
  public static final int OPEN = 2;
  public static final int CLOSE = 3;
  public static final int EOF = 0;
  public static final int VARIABLE = 4;
}

